### ISSUE TITLE
Error "Resource not found"

### ISSUE THREAD

**Issue by enusterch** [MikeGratsas/System.Windows.Forms.Controls#2]
Hello, 

the DataGrid is not working. When painting, is looks for resources (bitmaps), which seem to be not available.

![image](https://github.com/MikeGratsas/System.Windows.Forms.Controls/assets/170926221/e9e29733-a549-4e74-955f-37913f5a093f)

I found the following functions which are effected:

![image](https://github.com/MikeGratsas/System.Windows.Forms.Controls/assets/170926221/e07da93b-3f64-4e8a-ba81-20ea60fcf7cb)

Could you please fix it?

For me would be also OK. whem it just draws it with empty Bitmaps.

Thanks

Cheers

**Comment by MikeGratsas** [comment]
I added the missing DataGrid resources to the latest package version 1.0.5002
